### ISSUE TITLE
mocha.opts support?

### ISSUE THREAD

**Issue by shinout** [kt3k/kocha#18]
https://mochajs.org/#mochaopts

`kocha.opts` ?

**Comment by kt3k** [comment]
`mocha.opts` seems a little bit old-fashioned way to configure the behavior of cli.

babel has `.babelrc`. eslint has `.eslintrc`. webpack has `webpack.config.js`. karma has `karma.conf.js`. The current trends of config files are towards `json` or `js`, optionally `.yml`.

I prefer not following `mocha.opts` style to configure the cli.

**Comment by shinout** [comment]
OK, understood.
